authentication/urls.py
from django.urls import path
from authentication import views

app_name = "authentication"


urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
    path("user-action/<int:user_id>/", views.user_action, name="user_action"),
    path("verify-email/", views.verify_email, name="verify_email"),
    path("resend-otp/", views.resend_otp, name="resend_otp"),
    path("forget-password/", views.forget_password, name="forget_password"),
    path("change-password/", views.change_password, name="change_password"),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add-to-cart/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove-from-cart/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart",
    ),
    path("update_quantity/", views.update_quantity, name="update_quantity"),
    path("checkout/", views.checkout, name="checkout"),
    path("place-order/", views.place_order, name="place_order"),
    path("check-stock/", views.check_stock, name="check_stock"),
    path("order-success/", views.order_success, name="order_success"),
    path(
        "order-status/<int:order_id>/<str:status>/",
        views.order_status,
        name="order_status",
    ),
    path("remove-coupon/", views.remove_coupon, name="remove_coupon"),
]

techify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Django admin-panel Url
    path("django-admin/", admin.site.urls),
    # Custom admin-panel Url
    path("techify-admin/", include("admin_techify.urls")),
    # Custom Apps Urls
    path("", include("home.urls")),
    path("category/", include("category.urls")),
    path("brand/", include("brand.urls")),
    path("product/", include("product.urls")),
    path("offer/", include("offer.urls")),
    path("authentication/", include("authentication.urls")),
    path("cart/", include("cart.urls")),
    path("account/", include("account.urls")),
    path("wishlist/", include("wishlist.urls")),
    path("coupon/", include("coupon.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models


# Custom User Manager
class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("email should be given")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


# Custom User
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=150)
    referral_code = models.CharField(max_length=8, unique=True, null=True, blank=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name"]

    objects = CustomUserManager()

authentication/views.py
import random
from datetime import timedelta

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.utils import timezone

from authentication.models import User
from authentication.utils import add_referral_money


# Send otp to mail
def send_otp(request):
    otp = random.randint(1000, 9999)
    request.session["generated_otp"] = otp
    otp_expiry_time = timezone.now() + timedelta(minutes=5)
    request.session["otp_expiry_time"] = otp_expiry_time.isoformat()

    request.session["message"] = "otp has sent to your email"

    user_name = request.session.get("name", "Sir/Mam")
    subject = "Techify Ecommerce"
    message = f"Hi {user_name},\n\n{otp} is your OTP for email verification.\nOTP is valid for 5 min"
    recipient = request.session.get("email")
    send_mail(
        subject, message, settings.EMAIL_HOST_USER, [recipient], fail_silently=True
    )


# Resend otp
def resend_otp(request):
    request.session.pop("generated_otp", None)
    send_otp(request)
    return redirect("authentication:verify_email")


# Verify email using otp and save user
def verify_email(request):
    email = request.session.get("email")
    password = request.session.get("password")
    name = request.session.get("name")
    otp_expiry_time = request.session.get("otp_expiry_time")
    otp_expiry_time = timezone.datetime.fromisoformat(otp_expiry_time)

    # otp sended success message
    if "message" in request.session:
        message = request.session.pop("message")
    else:
        message = None

    if request.method == "POST":
        if timezone.now() > otp_expiry_time:
            request.session.pop("generated_otp", None)

        otp1 = request.POST.get("otp1")
        otp2 = request.POST.get("otp2")
        otp3 = request.POST.get("otp3")
        otp4 = request.POST.get("otp4")
        otp_code = otp1 + otp2 + otp3 + otp4

        generated_otp = request.session.get("generated_otp")
        if generated_otp is None:
            generated_otp = 00000

        if int(generated_otp) == int(otp_code):
            request.session.pop("generated_otp", None)
            if "forget_password" in request.session:
                request.session.pop("forget_password", None)
                return redirect("authentication:change_password")
            else:
                User.objects.create_user(email=email, password=password, name=name)
                user = authenticate(request, email=email, password=password)
                login(request, user)
                if "referral_code" in request.session:
                    referral_code = request.session.pop("referral_code")
                    add_referral_money(user, referral_code)
                request.session.pop("password", None)
                request.session.pop("email", None)
                request.session.pop("name", None)
                request.session["message"] = "signed in successfully"
                return redirect("home:home_page")
        else:
            messages.error(request, "Invalid OTP Please try again")

    context = {"email": email, "message": message}
    return render(request, "authentication/otp.html", context)


# Sign Up
def signup(request):
    if request.user.is_authenticated:
        return redirect("home:home_page")

    if request.method == "POST":
        name = request.POST.get("fullname")
        email = request.POST.get("email")
        password = request.POST.get("password")
        referral_code = request.POST.get("referral_code")

        if User.objects.filter(email=email).exists():
            message = "Email you had entered is already taken"
            return render(request, "authentication/signup.html", {"message": message})

        if len(referral_code) > 0:
            if not User.objects.filter(referral_code=referral_code).exists():
                message = "Invalid Referral Code"
                return render(
                    request, "authentication/signup.html", {"message": message}
                )
            else:
                request.session["referral_code"] = referral_code

        request.session["name"] = name
        request.session["email"] = email
        request.session["password"] = password

        send_otp(request)

        return redirect("authentication:verify_email")
    return render(request, "authentication/signup.html")


# Sign In
def signin(request):
    if request.user.is_authenticated:
        return redirect("home:home_page")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            get_user = User.objects.get(email=email)
        except ObjectDoesNotExist:
            user_isnotvalid = True
            return render(
                request,
                "authentication/signin.html",
                {"user_isnotvalid": user_isnotvalid},
            )

        user = authenticate(request, email=email, password=password)

        if user is not None and get_user.is_superuser:
            login(request, user)
            return redirect("admin_techify:admin_dashboard")
        elif user is not None and get_user.is_active:
            login(request, user)
            request.session["message"] = "Signed In Successfully"
            return redirect("home:home_page")
        else:
            user_isnotvalid = True
            return render(
                request,
                "authentication/signin.html",
                {"user_isnotvalid": user_isnotvalid},
            )
    return render(request, "authentication/signin.html")


# Sign Out
def signout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("home:home_page")


# User Block/Unblock
def user_action(request, user_id):
    try:
        user = User.objects.get(id=user_id)
        if user.is_active:
            user.is_active = False
        else:
            user.is_active = True
        user.save()
    except ObjectDoesNotExist:
        return redirect("admin_techify:user_management")
    return redirect("admin_techify:user_management")


# Forget Password (taking Email address from user and send otp)
def forget_password(request):
    if request.method == "POST":
        email = request.POST.get("email")
        if User.objects.filter(email=email).exists():
            request.session["email"] = email
            request.session["forget_password"] = "forget_password"
            send_otp(request)
            return redirect("authentication:verify_email")
        else:
            messages.error(request, "Email doesn't exists")
    return render(request, "authentication/password_assistance.html")


# Change Password (if the email is verified by otp)
def change_password(request):
    if "email" in request.session:
        email = request.session.get("email")
        if request.method == "POST":
            password = request.POST.get("password")
            try:
                user = User.objects.get(email=email)
                user.set_password(password)
                user.save()
                return redirect("authentication:signin")
            except ObjectDoesNotExist:
                return redirect("authentication:forget_password")

        return render(request, "authentication/change_password.html")
    return redirect("authentication:forget_password")

templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Title -->
        <title>{% block title %}{% endblock %}</title>
      <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}" >
      <!-- CSS -->
        {% block css %}
        {% endblock %}
    </head>
    <body>
      <!-- Content -->
        {% block content %}
        {% endblock %}
      <!-- JS -->
        {% block js %}
        {% endblock %}
    </body>
</html>

templates/authentication/otp.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Verify Email{% endblock %}
{% block css %}
<!-- Bootstrap 5 CDN Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'authentication/css/otp.css' %}">
{% endblock %}
{% block content %}
    <section class="wrapper">
        <div class="container">
            <div class="col-sm-8 offset-sm-2 col-lg-6 offset-lg-3 col-xl-6 offset-xl-3 text-center">
                <form class="rounded bg-white shadow p-5" method="POST" id="otpForm" action={% url 'authentication:verify_email' %}>
                    {% csrf_token %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <h3 class="text-dark fw-bolder fs-4 mb-2">Verify Email</h3>
                    <div class="fw-normal text-muted">
                        Enter the verification code sent to
                    </div>
                    <div class="d-flex align-items-center justify-content-center fw-bold mb-4">
                        <span>{{ email }}</span>
                    </div>
                    <div class="otp_input text-start mb-2">
                        <div class="d-flex align-items-center justify-content-evenly mt-2">
                            <input type="text" class="form-control otp" placeholder="" maxlength="1" name="otp1" data-index="1">
                            <input type="text" class="form-control otp" placeholder="" maxlength="1" name="otp2" data-index="2">
                            <input type="text" class="form-control otp" placeholder="" maxlength="1" name="otp3" data-index="3">
                            <input type="text" class="form-control otp" placeholder="" maxlength="1" name="otp4" data-index="4">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary submit_btn my-4">Submit</button>
                    <div class="fw-normal text-muted mb-2">
                        Didn’t get the code ? <a href="{% url 'authentication:resend_otp' %}" id="resend-otp" class="text-primary fw-bold text-decoration-none" hidden>Resend</a>
                        <p id="resend-message">Resend OTP in <span id="timer">60</span> seconds</p>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function() {
            $('#otpForm').submit(function(event) {
                var isValid = true;
                $('.otp').each(function() {
                    if ($(this).val() === '') {
                        isValid = false;
                        $(this).css('border-color', 'red');
                    }
                });
                if (!isValid) {
                    event.preventDefault();
                }
            });

            $('.otp').focus(function() {
                $(this).css('border-color', '');
            });
        });
        const timerElement = document.getElementById('timer');
        let seconds = 60;
        let timer;

        function updateTimer() {
            timerElement.textContent = seconds;
            if (seconds === 0) {
                clearInterval(timer);
                document.getElementById('resend-otp').removeAttribute('hidden');
                document.getElementById('resend-message').textContent = '';
            }
            seconds--;
        }

        function startTimer() {
            updateTimer();
            timer = setInterval(updateTimer, 1000);
        }

        startTimer();

        document.addEventListener('DOMContentLoaded', function() {
            const otpInputs = document.querySelectorAll('.otp');

            otpInputs.forEach(function(input) {
                input.addEventListener('input', function() {
                    const maxLength = parseInt(input.getAttribute('maxlength'));
                    const currentLength = input.value.length;

                    if (currentLength >= maxLength) {
                        const nextIndex = parseInt(input.getAttribute('data-index')) + 1;
                        const nextInput = document.querySelector(`input[data-index="${nextIndex}"]`);

                        if (nextInput) {
                            nextInput.focus();
                        }
                    } else if (currentLength === 0) {
                        const prevIndex = parseInt(input.getAttribute('data-index')) - 1;
                        const prevInput = document.querySelector(`input[data-index="${prevIndex}"]`);

                        if (prevInput) {
                            prevInput.focus();
                        }
                    }
                });
            });
        });
        {% if message %}
            const Toast = Swal.mixin({
                toast: true,
                position: "top",
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.onmouseenter = Swal.stopTimer;
                    toast.onmouseleave = Swal.resumeTimer;
                }
            });
            Toast.fire({
                icon: "success",
                title: "otp has sent to your email"
            });
        {% endif %}
    </script>
{% endblock %}

templates/authentication/signin.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Sign In{% endblock %}
{% block css %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'authentication/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="content" style="padding: 3rem 0;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                {% if user_isnotvalid %}
                                    <div class="alert alert-danger" role="alert">
                                        Invalid Credentials!
                                    </div>
                                {% endif %}
                                <div class="mb-6">
                                    <h3 style="text-align: center; margin-bottom: 40px;"><strong>Sign In</strong></h3>
                                </div>
                                <form action="{% url 'authentication:signin' %}" method="post" id="form">
                                    {% csrf_token %}
                                    <div class="form-group last mb-4">
                                        <input type="text" class="form-control" id="email" name="email" Placeholder="Email">
                                        <span id="email-error" class="text-danger"></span>
                                    </div>
                                    <div class="form-group last mb-4">
                                        <input type="password" class="form-control" id="password" name="password" Placeholder="Password">
                                        <span id="password-error" class="text-danger"></span>
                                    </div>
                                    <div class="d-flex mb-5 align-items-center">
                                        <span class="ml-auto"><a href="{% url 'authentication:forget_password' %}" class="forgot-pass" style="color: #3399ff;">Forgot Password?</a></span>
                                    </div>
                                    <input type="submit" value="Sign In" class="btn btn-pill text-white btn-block btn-primary" style="background: #3399ff;">
                                    <span class="d-block text-center my-4 text-muted"> Don't have an account? <a href='{% url 'authentication:signup' %}' style="color: #3399ff;">Sign Up</a></span>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'authentication/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'authentication/js/popper.min.js' %}"></script>
    <script src="{% static 'authentication/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'authentication/js/main.js' %}"></script>
    <script>
        document.getElementById("form").addEventListener("submit", function (event) {
            var email = document.getElementById("email").value.trim();
            var password = document.getElementById("password").value.trim();
            var isValid = true;

            if (email === "") {
                isValid = false;
                document.getElementById("email-error").textContent = "Please enter your email address.";
            } else if (!isValidEmail(email)) {
                isValid = false;
                document.getElementById("email-error").textContent = "Please enter a valid email address.";
            } else {
                document.getElementById("email-error").textContent = "";
            }

            if (password === "") {
                isValid = false;
                document.getElementById("password-error").textContent = "Please enter your password.";
            } else {
                document.getElementById("password-error").textContent = "";
            }

            if (!isValid) {
                event.preventDefault();
            }
        });

        function isValidEmail(email) {
            var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return emailRegex.test(email);
        }

    </script>
{% endblock %}

templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %}Sign Up{% endblock %}
{% block css %}
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'authentication/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'authentication/css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="content" style="padding: 2rem 0;">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 contents">
                    <div class="row justify-content-center">
                        <div class="col-md-12">
                            <div class="form-block">
                                <div class="mb-6">
                                    <h3 style="text-align: center; margin-bottom: 50px;"><strong>Sign Up</strong></h3>
                                </div>
                                {% if message %}
                                    <div class="alert alert-danger" role="alert">
                                        {{ message }}
                                    </div>
                                {% endif %}
                                <form action="{% url 'authentication:signup' %}" method="post" id="form">
                                    {% csrf_token %}
                                    <div class="form-group first">
                                        <input type="text" class="form-control mb-2" id="fullname" name="fullname" Placeholder="Full Name" >
                                        <span id="fullname-error" class="text-danger"></span>
                                    </div>
                                    <div class="form-group last">
                                        <input type="text" class="form-control" id="email" name="email" Placeholder="Email">
                                        <span id="email-error" class="text-danger"></span>
                                    </div>
                                    <div class="form-group last">
                                        <input type="password" class="form-control" id="password" name="password" Placeholder="Password">
                                        <span id="password-error" class="text-danger"></span>
                                    </div>
                                    <div class="form-group last mb-5">
                                        <input type="text" class="form-control" id="referral_code" name="referral_code" Placeholder="Referral Code (optional)">
                                    </div>
                                    <input type="submit" value="Sign Up" class="btn btn-pill text-white btn-block btn-primary" style="background: #3399ff;">
                                    <span class="d-block text-center my-4 text-muted"> Already have an account? <a href='{% url 'authentication:signin' %}' style="color: #3399ff;">Sign In</a></span>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'authentication/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'authentication/js/popper.min.js' %}"></script>
    <script src="{% static 'authentication/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'authentication/js/main.js' %}"></script>
    <script>
        document.getElementById("form").addEventListener("submit", function (event) {
            var fullname = document.getElementById("fullname").value.trim();
            var email = document.getElementById("email").value.trim();
            var password = document.getElementById("password").value.trim();
            var isValid = true;

            // Regular expression to allow only letters and spaces
            var nameRegex = /^[A-Za-z\s]+$/;

            if (fullname === "") {
                isValid = false;
                document.getElementById("fullname-error").textContent = "Please enter your full name.";
            } else if (!nameRegex.test(fullname)) {
                isValid = false;
                document.getElementById("fullname-error").textContent = "Enter a valid name.";
            } else {
                document.getElementById("fullname-error").textContent = "";
            }

            if (email === "") {
                isValid = false;
                document.getElementById("email-error").textContent = "Please enter your email address.";
            } else if (!isValidEmail(email)) {
                isValid = false;
                document.getElementById("email-error").textContent = "Please enter a valid email address.";
            } else {
                document.getElementById("email-error").textContent = "";
            }

            if (password === "") {
                isValid = false;
                document.getElementById("password-error").textContent = "Please enter your password.";
            } else if (!isValidPassword(password)) {
                isValid = false;
                document.getElementById("password-error").textContent = "Password must contain at least 8 characters, 1 capital letter and 1 symbol.";
            } else {
                document.getElementById("password-error").textContent = "";
            }

            if (!isValid) {
                event.preventDefault();
            }
        });

        function isValidEmail(email) {
            var emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            return emailRegex.test(email);
        }

        function isValidPassword(password) {
            var passwordRegex = /^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.{8,})/;
            return passwordRegex.test(password);
        }
    </script>
{% endblock %}