admin_techify/urls.py
from django.urls import path
from admin_techify import views

app_name = "admin_techify"


urlpatterns = [
    path("", views.admin_dashboard, name="admin_dashboard"),
    path("category-management/", views.category_management, name="category_management"),
    path("brand-management/", views.brand_management, name="brand_management"),
    path("user-management/", views.user_management, name="user_management"),
    path("product-management/", views.product_management, name="product_management"),
    path("order-management/", views.order_management, name="order_management"),
    path("order-details/<int:order_id>/", views.order_details, name="order_details"),
    path("coupon-management/", views.coupon_management, name="coupon_management"),
    path("offer-management/", views.offer_management, name="offer_management"),
    path("sales-report/", views.sales_report, name="sales_report"),
    path("generate-pdf/", views.generate_pdf, name="generate_pdf"),
    path("generate-excel/", views.generate_excel, name="generate_excel"),
]

brand/urls.py
from django.urls import path
from brand import views

app_name = "brand"


urlpatterns = [
    path("add-brand/", views.add_brand, name="add_brand"),
    path("edit-brand/<int:brand_id>/", views.edit_brand, name="edit_brand"),
    path("brand-action/<int:brand_id>/", views.brand_action, name="brand_action"),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add-to-cart/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove-from-cart/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart",
    ),
    path("update_quantity/", views.update_quantity, name="update_quantity"),
    path("checkout/", views.checkout, name="checkout"),
    path("place-order/", views.place_order, name="place_order"),
    path("check-stock/", views.check_stock, name="check_stock"),
    path("order-success/", views.order_success, name="order_success"),
    path(
        "order-status/<int:order_id>/<str:status>/",
        views.order_status,
        name="order_status",
    ),
    path("remove-coupon/", views.remove_coupon, name="remove_coupon"),
]

category/urls.py
from django.urls import path
from category import views

app_name = "category"


urlpatterns = [
    path(
        "category-action/<int:category_id>/",
        views.category_action,
        name="category_action",
    ),
    path("add-category/", views.add_category, name="add_category"),
    path("edit-category/<int:category_id>/", views.edit_category, name="edit_category"),
]

coupon/urls.py
from django.urls import path
from coupon import views

app_name = "coupon"


urlpatterns = [
    path("add-coupon/", views.add_coupon, name="add_coupon"),
    path("edit-coupon/<int:coupon_id>/", views.edit_coupon, name="edit_coupon"),
    path("remove-coupon/<int:coupon_id>/", views.remove_coupon, name="remove_coupon"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"


urlpatterns = [
    path("", views.home, name="home_page"),
]

offer/urls.py
from django.urls import path
from offer import views

app_name = "offer"


urlpatterns = [
    path("add-offer/", views.add_offer, name="add_offer"),
    path("edit-offer/<int:offer_id>/", views.edit_offer, name="edit_offer"),
    path("remove-offer/<int:offer_id>/", views.remove_offer, name="remove_offer"),
    path(
        "product-offer/<int:product_id>/<int:offer_id>/",
        views.product_offer,
        name="product_offer",
    ),
    path(
        "remove-product-offer/<int:product_id>/",
        views.remove_product_offer,
        name="remove_product_offer",
    ),
    path(
        "category-offer/<int:category_id>/<int:offer_id>/",
        views.category_offer,
        name="category_offer",
    ),
    path(
        "remove-category-offer/<int:category_id>/",
        views.remove_category_offer,
        name="remove_category_offer",
    ),
]

product/urls.py
from django.urls import path
from product import views

app_name = "product"


urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("product-view/<int:product_id>/", views.product_view, name="product_view"),
    path("add-product/", views.add_product, name="add_product"),
    path("edit-product/<int:product_id>/", views.edit_product, name="edit_product"),
    path(
        "product-action/<int:product_id>/", views.product_action, name="product_action"
    ),
    path("add_review/", views.add_review, name="add_review"),
]

brand/models.py
from django.db import models


# Brand
class Brand(models.Model):
    name = models.CharField(max_length=100, unique=True)
    is_available = models.BooleanField(default=True)

category/models.py
import os

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from offer.models import Offer


# Category Model
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to="images/category")
    offer = models.ForeignKey(Offer, on_delete=models.SET_NULL, null=True)
    is_available = models.BooleanField(default=True)


# To delete old category images before saving new images
@receiver(pre_save, sender=Category)
def delete_old_image(sender, instance, **kwargs):
    if instance.pk:
        try:
            old_instance = sender.objects.get(pk=instance.pk)
        except sender.DoesNotExist:
            return
        else:
            if old_instance.image != instance.image:
                old_image_path = old_instance.image.path
                if os.path.isfile(old_image_path):
                    os.remove(old_image_path)

coupon/models.py
from django.db import models

from authentication.models import User


# Coupon
class Coupon(models.Model):
    name = models.CharField(max_length=150)
    code = models.CharField(max_length=150)
    discount_percentage = models.IntegerField()
    limit = models.IntegerField()
    expiry_date = models.DateField()


# Coupon Usage Data
class CouponUsage(models.Model):
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

brand/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from brand.models import Brand


# Add brand
@login_required(login_url="authentication:signin")
def add_brand(request):
    if request.user.is_superuser:
        if request.method == "POST":
            brand_name = request.POST.get("brand_name")
            name = brand_name.lstrip()

            if Brand.objects.filter(name__iexact=name).exists():
                brand_exists = True
                return render(
                    request,
                    "custom_admin/add_brand.html",
                    {"brand_exists": brand_exists},
                )

            new_brand = Brand.objects.create(name=name)
            new_brand.save()
            request.session["brand_message"] = f"{name} Brand Added"
            return redirect("admin_techify:brand_management")

        return render(request, "custom_admin/add_brand.html")
    return redirect("home:home_page")


# Edit brand
@login_required(login_url="authentication:signin")
def edit_brand(request, brand_id):
    if request.user.is_superuser:
        try:
            update_brand = Brand.objects.get(id=brand_id)
        except ObjectDoesNotExist:
            return redirect("admin_techify:brand_management")

        if request.method == "POST":
            brand_name = request.POST.get("brand_name")
            name = brand_name.lstrip()

            if (
                Brand.objects.filter(name__iexact=name)
                .exclude(name=update_brand.name)
                .exists()
            ):
                brand_exists = True
                context = {
                    "brand_exists": brand_exists,
                    "brand": update_brand,
                }
                return render(request, "custom_admin/edit_brand.html", context)

            update_brand.name = name
            update_brand.save()
            request.session["brand_message"] = f"{name} Brand Updated"
            return redirect("admin_techify:brand_management")

        return render(request, "custom_admin/edit_brand.html", {"brand": update_brand})
    return redirect("home:home_page")


# Brand Block/Unblock
@login_required(login_url="authentication:signin")
def brand_action(request, brand_id):
    if request.user.is_superuser:
        try:
            brand = Brand.objects.get(id=brand_id)
            if brand.is_available:
                brand.is_available = False
            else:
                brand.is_available = True
            brand.save()
        except ObjectDoesNotExist:
            return redirect("admin_techify:brand_management")

        return redirect("admin_techify:brand_management")
    return redirect("home:home_page")

category/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from category.models import Category
from utils.utils import validate_image


# Category Block/Unblock
@login_required(login_url="authentication:signin")
def category_action(request, category_id):
    if request.user.is_superuser:
        try:
            category = Category.objects.get(id=category_id)
            if category.is_available:
                category.is_available = False
            else:
                category.is_available = True
            category.save()
        except ObjectDoesNotExist:
            return redirect("admin_techify:category_management")

        return redirect("admin_techify:category_management")
    return redirect("home:home_page")


# Add Category
@login_required(login_url="authentication:signin")
def add_category(request):
    if request.user.is_superuser:
        # category image validation error message
        if "message" in request.session:
            message = request.session.pop("message")
        else:
            message = None

        if request.method == "POST":
            name = request.POST.get("category_name")
            category_img = request.FILES.get("category_image")
            category_name = name.lstrip()

            if Category.objects.filter(name__iexact=category_name).exists():
                category_exists = True
                return render(
                    request,
                    "custom_admin/add_category.html",
                    {"category_exists": category_exists},
                )
            if not validate_image(category_img):
                request.session["message"] = "image_not_valid"
                return redirect("category:add_category")

            add_category = Category.objects.create(
                name=category_name, image=category_img
            )
            add_category.save()
            request.session["category_message"] = f"{category_name} Category Added"

            return redirect("admin_techify:category_management")

        return render(request, "custom_admin/add_category.html", {"message": message})
    return redirect("home:home_page")


# Edit Category
@login_required(login_url="authentication:signin")
def edit_category(request, category_id):
    if request.user.is_superuser:
        try:
            edit_category = Category.objects.get(id=category_id)
        except ObjectDoesNotExist:
            return redirect("admin_techify:category_management")

        # category image validation error message
        if "message" in request.session:
            message = request.session.pop("message")
        else:
            message = None

        if request.method == "POST":
            name = request.POST.get("category_name")
            category_img = request.FILES.get("category_image")
            category_name = name.lstrip()

            url = reverse("category:edit_category", kwargs={"category_id": category_id})

            if (
                Category.objects.filter(name__iexact=category_name)
                .exclude(name=edit_category.name)
                .exists()
            ):
                category_exists = True
                context = {
                    "category_exists": category_exists,
                    "edit_category": edit_category,
                }
                return render(request, "custom_admin/edit_category.html", context)

            edit_category.name = category_name
            if category_img:
                if not validate_image(category_img):
                    request.session["message"] = "image_not_valid"
                    return redirect(url)
                edit_category.image = category_img
            edit_category.save()
            request.session["category_message"] = f"{category_name} Category Updated"

            return redirect("admin_techify:category_management")

        context = {"edit_category": edit_category, "message": message}
        return render(request, "custom_admin/edit_category.html", context)
    return redirect("home:home_page")

coupon/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from datetime import datetime

from coupon.models import Coupon


# Add Coupon
@login_required(login_url="authentication:signin")
def add_coupon(request):
    if request.user.is_superuser:
        if request.method == "POST":
            coupon_name = request.POST.get("coupon_name")
            coupon_code = request.POST.get("coupon_code")
            discount_percentage = request.POST.get("discount")
            user_limit = request.POST.get("user_limit")
            expiry_date = request.POST.get("expiry_date")

            expiry_date = datetime.strptime(expiry_date, "%Y-%m-%d").date()

            if Coupon.objects.filter(name__iexact=coupon_name).exists():
                error_message = "Coupon name already exists."
                return render(
                    request, "admin/add_coupon.html", {"error_message": error_message}
                )

            if Coupon.objects.filter(code__iexact=coupon_code).exists():
                error_message = "Coupon code already exists."
                return render(
                    request, "admin/add_coupon.html", {"error_message": error_message}
                )

            new_coupon = Coupon.objects.create(
                name=coupon_name,
                code=coupon_code,
                discount_percentage=discount_percentage,
                limit=user_limit,
                expiry_date=expiry_date,
            )
            new_coupon.save()

            request.session["coupon_message"] = f"{coupon_name} Coupon Added"

            return redirect("admin_techify:coupon_management")

        return render(request, "custom_admin/add_coupon.html")
    return redirect("home:home_page")


# Edit Coupon
@login_required(login_url="authentication:signin")
def edit_coupon(request, coupon_id):
    if request.user.is_superuser:
        try:
            update_coupon = Coupon.objects.get(id=coupon_id)
            expiry_date = update_coupon.expiry_date.strftime("%Y-%m-%d")
        except ObjectDoesNotExist:
            return redirect("admin_techify:coupon_management")

        if request.method == "POST":
            coupon_name = request.POST.get("coupon_name")
            coupon_code = request.POST.get("coupon_code")
            discount_percentage = request.POST.get("discount")
            user_limit = request.POST.get("user_limit")
            expiry_date = request.POST.get("expiry_date")

            expiry_date = datetime.strptime(expiry_date, "%Y-%m-%d").date()

            if (
                Coupon.objects.filter(name__iexact=coupon_name)
                .exclude(name=update_coupon.name)
                .exists()
            ):
                error_message = "Coupon name already exists."
                context = {
                    "error_message": error_message,
                    "update_coupon": update_coupon,
                }
                return render(request, "custom_admin/edit_coupon.html", context)

            if (
                Coupon.objects.filter(code__iexact=coupon_code)
                .exclude(code=update_coupon.code)
                .exists()
            ):
                error_message = "Coupon code already exists."
                context = {
                    "error_message": error_message,
                    "update_coupon": update_coupon,
                }
                return render(request, "custom_admin/edit_coupon.html", context)

            update_coupon.name = coupon_name
            update_coupon.code = coupon_code
            update_coupon.discount_percentage = discount_percentage
            update_coupon.limit = user_limit
            update_coupon.expiry_date = expiry_date
            update_coupon.save()

            request.session["coupon_message"] = f"{coupon_name} Coupon Updated"

            return redirect("admin_techify:coupon_management")

        context = {"update_coupon": update_coupon, "expiry_date": expiry_date}
        return render(request, "custom_admin/edit_coupon.html", context)
    return redirect("home:home_page")


# Delete Coupon
@login_required(login_url="authentication:signin")
def remove_coupon(request, coupon_id):
    if request.user.is_superuser:
        try:
            coupon = Coupon.objects.get(id=coupon_id)
            coupon.delete()
        except ObjectDoesNotExist:
            return redirect("admin_techify:coupon_management")

        return redirect("admin_techify:coupon_management")
    return redirect("home:home_page")

templates/custom_admin/add_brand.html
{% extends 'custom_admin/base.html' %}
{% load static %}
{% block title %}Add Brand{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/assets/css/style.css' %}">
{% endblock %}
{% block content %}
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title">Add New Brand</h3>
            </div>
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        {% if brand_exists %}
                            <div class="alert alert-danger" role="alert">
                                Brand already exists
                            </div>
                        {% endif %}
                        <form class="forms-sample" method="post" action="{% url 'brand:add_brand' %}" enctype="multipart/form-data" onsubmit="return validateForm()">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="brandName">Brand Name</label>
                                <input type="text" style="color: white;" class="form-control" id="brandName" placeholder="Enter Brand Name" name="brand_name">
                                <span id="brandNameError" style="color: red; font-size: 12px;"></span>
                            </div>
                            <div style="display: flex; justify-content: end; margin-top: 2rem">
                                <a href="{% url 'admin_techify:brand_management' %}" class="btn btn-dark mr-2">Back</a>
                                <button type="submit" class="btn btn-success">Add</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'admin/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <script src="{% static 'admin/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'admin/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'admin/assets/js/misc.js' %}"></script>
    <script src="{% static 'admin/assets/js/settings.js' %}"></script>
    <script src="{% static 'admin/assets/js/todolist.js' %}"></script>
    <script>
        function validateForm() {
            var brandName = document.getElementById("brandName").value;
            var brandNameError = document.getElementById("brandNameError");
            var isValid = true;

            brandNameError.innerHTML = "";

            if (brandName.trim().length === 0) {
                brandNameError.innerHTML = "Enter a brand name.";
                isValid = false;
            }
            return isValid;
        }
    </script>
{% endblock %}

templates/custom_admin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Title -->
        <title>{% block title %}{% endblock %}</title>
      <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}" >
      <!-- CSS -->
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="container-scroller">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top" style="background: white;">
                    <a class="sidebar-brand brand-logo" href="{% url 'admin_techify:admin_dashboard' %}" style="padding-left: 3rem;"><img src="{% static 'user/assets/images/techify-logo.png' %}" alt="logo" style="height: 40px;" /></a>
                    <a class="sidebar-brand brand-logo-mini" href="{% url 'admin_techify:admin_dashboard' %}"><img src="{% static 'user/assets/images/techify-icon-nobg.png' %}" alt="logo" style="width: 29px;"/></a>
                </div>
                <ul class="nav">
                    <li class="nav-item nav-category">
                        <span class="nav-link">Navigation</span>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'admin_dashboard' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:admin_dashboard' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-speedometer"></i>
                            </span>
                            <span class="menu-title">Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'user_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:user_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-account"></i>
                            </span>
                            <span class="menu-title">Users</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'brand_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:brand_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-format-list-bulleted"></i>
                            </span>
                            <span class="menu-title">Brand</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'category_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:category_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-playlist-play"></i>
                            </span>
                            <span class="menu-title">Category</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'product_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:product_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-view-list"></i>
                            </span>
                            <span class="menu-title">Product</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'order_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:order_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-chart-bar"></i>
                            </span>
                            <span class="menu-title">Orders</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'coupon_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:coupon_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi mdi-tag"></i>
                            </span>
                            <span class="menu-title">Coupon</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'offer_management' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:offer_management' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi mdi-sale"></i>
                            </span>
                            <span class="menu-title">Offer</span>
                        </a>
                    </li>
                    <li class="nav-item menu-items {% if request.resolver_match.url_name == 'sales_report' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'admin_techify:sales_report' %}">
                            <span class="menu-icon">
                                <i class="mdi mdi-elevation-rise"></i>
                            </span>
                            <span class="menu-title">Sales Report</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="container-fluid page-body-wrapper">
                <nav class="navbar p-0 fixed-top d-flex flex-row">
                    <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
                        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="{% static 'user/assets/images/techify-icon-nobg.png' %}"
                                                                                       alt="logo" /></a>
                    </div>
                    <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
                        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                            <span class="mdi mdi-menu"></span>
                        </button>
                        <ul class="navbar-nav navbar-nav-right">
                            <li class="nav-item dropdown">
                                <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown" style="margin-left:0px;">
                                    <div class="navbar-profile">
                                        <p class="mb-0 d-none d-sm-block navbar-profile-name" style="margin-left:0px;">Admin</p>
                                        <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                                    </div>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                                     aria-labelledby="profileDropdown">
                                    <h6 class="p-3 mb-0">Profile</h6>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item preview-item" href="{% url 'home:home_page' %}">
                                        <div class="preview-thumbnail">
                                            <div class="preview-icon bg-dark rounded-circle">
                                                <i class="mdi mdi-settings text-success"></i>
                                            </div>
                                        </div>
                                        <div class="preview-item-content">
                                            <p class="preview-subject mb-1">Go To User Side</p>
                                        </div>
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item preview-item" href="{% url 'authentication:signout' %}">
                                        <div class="preview-thumbnail">
                                            <div class="preview-icon bg-dark rounded-circle">
                                                <i class="mdi mdi-logout text-danger"></i>
                                            </div>
                                        </div>
                                        <div class="preview-item-content">
                                            <p class="preview-subject mb-1">Logout</p>
                                        </div>
                                    </a>
                                </div>
                            </li>
                        </ul>
                        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
                                data-toggle="offcanvas">
                            <span class="mdi mdi-format-line-spacing"></span>
                        </button>
                    </div>
                </nav>
            <!-- Content -->
                {% block content %}
                {% endblock %}
            </div>
        </div>
      <!-- JS -->
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        {% block js %}
        {% endblock %}
    </body>
</html>