account/urls.py
from django.urls import path
from account import views

app_name = "account"


urlpatterns = [
    path("", views.account_settings, name="account_settings"),
    path("referral-code", views.generate_referral_code, name="get_referral_code"),
    path("orders/", views.orders, name="orders"),
    path("order-details/<int:order_id>/", views.order_details, name="order_details"),
    path(
        "download-invoice/<int:order_id>/",
        views.download_product_invoice,
        name="download_invoice",
    ),
    path("address/", views.address, name="address"),
    path("add-address/", views.add_address, name="add_address"),
    path(
        "remove-address/<int:address_id>/", views.remove_address, name="remove_address"
    ),
    path("edit-address/<int:address_id>/", views.edit_address, name="edit_address"),
    path("wallet/", views.wallet, name="wallet"),
    path("change-password/", views.change_password, name="change_password"),
]

cart/urls.py
from django.urls import path
from cart import views

app_name = "cart"


urlpatterns = [
    path("", views.cart, name="cart"),
    path("add-to-cart/", views.add_to_cart, name="add_to_cart"),
    path(
        "remove-from-cart/<int:item_id>/",
        views.remove_from_cart,
        name="remove_from_cart",
    ),
    path("update_quantity/", views.update_quantity, name="update_quantity"),
    path("checkout/", views.checkout, name="checkout"),
    path("place-order/", views.place_order, name="place_order"),
    path("check-stock/", views.check_stock, name="check_stock"),
    path("order-success/", views.order_success, name="order_success"),
    path(
        "order-status/<int:order_id>/<str:status>/",
        views.order_status,
        name="order_status",
    ),
    path("remove-coupon/", views.remove_coupon, name="remove_coupon"),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"


urlpatterns = [
    path("", views.home, name="home_page"),
]

product/urls.py
from django.urls import path
from product import views

app_name = "product"


urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("product-view/<int:product_id>/", views.product_view, name="product_view"),
    path("add-product/", views.add_product, name="add_product"),
    path("edit-product/<int:product_id>/", views.edit_product, name="edit_product"),
    path(
        "product-action/<int:product_id>/", views.product_action, name="product_action"
    ),
    path("add_review/", views.add_review, name="add_review"),
]

techify/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Django admin-panel Url
    path("django-admin/", admin.site.urls),
    # Custom admin-panel Url
    path("techify-admin/", include("admin_techify.urls")),
    # Custom Apps Urls
    path("", include("home.urls")),
    path("category/", include("category.urls")),
    path("brand/", include("brand.urls")),
    path("product/", include("product.urls")),
    path("offer/", include("offer.urls")),
    path("authentication/", include("authentication.urls")),
    path("cart/", include("cart.urls")),
    path("account/", include("account.urls")),
    path("wishlist/", include("wishlist.urls")),
    path("coupon/", include("coupon.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.utils import timezone

from authentication.models import User


# User address
class UserAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    landmark = models.CharField(max_length=255, null=True)


# Wallet
class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=30, decimal_places=1, null=True)


# Wallet transactions
class WalletTransaction(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    description = models.CharField(max_length=255)
    amount = models.DecimalField(max_digits=30, decimal_places=1)
    date_time = models.DateTimeField(default=timezone.now)
    is_credit = models.BooleanField()

cart/models.py
from django.db import models

from product.models import Product
from authentication.models import User


# Cart Data
class CartItems(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    @property
    def total(self):
        return self.product.price * self.quantity


# Delivery Address
class DeliveyAddress(models.Model):
    name = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    landmark = models.CharField(max_length=255, null=True)


# Order Data
class Orders(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered_date = models.DateField()
    delivered_date = models.DateField(null=True)
    payment_method = models.CharField(max_length=100)
    status = models.CharField(max_length=100, default="Pending")
    return_status = models.CharField(max_length=100, null=True, blank=True)
    address = models.ForeignKey(DeliveyAddress, on_delete=models.CASCADE)
    discount_amt = models.DecimalField(max_digits=30, decimal_places=1, default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_price = models.DecimalField(max_digits=30, decimal_places=1)
    product_qty = models.PositiveIntegerField()

    @property
    def sub_total(self):
        return self.product_price * self.product_qty

    @property
    def total(self):
        return self.sub_total - self.discount_amt

wishlist/models.py
from django.db import models

from product.models import Product
from authentication.models import User


# Wishlist Data
class Wishlist(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

account/views.py
import random
import string
from io import BytesIO

from xhtml2pdf import pisa

from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponse
from django.template.loader import get_template
from django.core.paginator import Paginator

from authentication.models import User
from account.models import UserAddress, Wallet, WalletTransaction
from cart.models import Orders
from product.models import ProductReview


# Account Settings
@login_required(login_url="authentication:signin")
def account_settings(request):
    user_id = request.user.id
    message = False
    try:
        user = User.objects.get(id=user_id)
    except ObjectDoesNotExist:
        return redirect("authentication:signin")

    if request.method == "POST":
        name = request.POST.get("name")
        user.name = name
        user.save()
        message = "name_updated"

    context = {"user": user, "message": message}
    return render(request, "user/account.html", context)


# Generate Referral code
@login_required(login_url="authentication:signin")
def generate_referral_code(request):
    user_id = request.user.id
    try:
        user = User.objects.get(id=user_id)
    except ObjectDoesNotExist:
        return redirect("authentication:signin")

    while True:
        characters = string.ascii_letters + string.digits
        referral_code = "".join(random.choice(characters) for _ in range(8))

        if not User.objects.filter(referral_code=referral_code).exists():
            break

    user.referral_code = referral_code
    user.save()
    return redirect("account:account_settings")


# Orders
@login_required(login_url="authentication:signin")
def orders(request):
    user_id = request.user.id
    ordered_products = (
        Orders.objects.filter(user=user_id)
        .select_related("address", "product")
        .order_by("-id")
    )
    paginator = Paginator(ordered_products, 5)
    page_number = request.GET.get("page")
    ordered_obj = paginator.get_page(page_number)

    return render(request, "user/list_orders.html", {"ordered_obj": ordered_obj})


# Order Details
@login_required(login_url="authentication:signin")
def order_details(request, order_id):
    try:
        order = Orders.objects.get(id=order_id)
        return_order = False
        if order.status == "Delivered":
            delivered_date = order.delivered_date
            today_date = timezone.now().date()
            difference = (today_date - delivered_date).days
            if difference <= 7:
                return_order = True

        write_review = written_review = False
        if order.status == "Delivered" or order.status == "Returned":
            write_review = True
            written_review = ProductReview.objects.filter(
                user=request.user, product=order.product
            ).first()
            if written_review:
                write_review = False

        if "review_message" in request.session:
            review_message = request.session.pop("review_message")
        else:
            review_message = False

        context = {
            "order": order,
            "return_order": return_order,
            "review_message": review_message,
            "write_review": write_review,
            "written_review": written_review,
        }
        return render(request, "user/order_details.html", context)
    except ObjectDoesNotExist:
        return redirect("account:orders")


# Fetch User Addresses
@login_required(login_url="authentication:signin")
def address(request):
    user_id = request.user.id
    addresses = UserAddress.objects.filter(user=user_id)

    # Success message of Address Added/Edited
    if "message" in request.session:
        message = request.session.pop("message")
    else:
        message = False

    context = {
        "addresses": addresses,
        "message": message,
    }
    return render(request, "user/address.html", context)


# Remove Address
@login_required(login_url="authentication:signin")
def remove_address(request, address_id):
    previous_url = request.META.get("HTTP_REFERER")

    try:
        address = UserAddress.objects.get(id=address_id)
        address.delete()
    except ObjectDoesNotExist:
        return redirect(previous_url)

    return redirect(previous_url)


# Add Address
@login_required(login_url="authentication:signin")
def add_address(request):
    previous_url = request.META.get("HTTP_REFERER")

    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        city = request.POST.get("city")
        landmark = request.POST.get("landmark")
        state = request.POST.get("state")
        country = request.POST.get("country")

        user_id = request.user.id
        previous_url = request.POST.get("previous_url")

        try:
            user = User.objects.get(id=user_id)
        except ObjectDoesNotExist:
            return redirect("authentication:signin")

        add_address = UserAddress.objects.create(
            user=user,
            name=name,
            phone=phone,
            city=city,
            landmark=landmark,
            state=state,
            country=country,
        )
        add_address.save()
        request.session["message"] = "address_added"

        return redirect(previous_url)

    return render(request, "user/add_address.html", {"previous_url": previous_url})


# Edit Address
@login_required(login_url="authentication:signin")
def edit_address(request, address_id):
    previous_url = request.META.get("HTTP_REFERER")

    try:
        address = UserAddress.objects.get(id=address_id)
    except ObjectDoesNotExist:
        return redirect(previous_url)

    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        city = request.POST.get("city")
        landmark = request.POST.get("landmark")
        state = request.POST.get("state")
        country = request.POST.get("country")
        previous_url = request.POST.get("previous_url")

        address.name = name
        address.phone = phone
        address.city = city
        address.landmark = landmark
        address.state = state
        address.country = country
        address.save()
        request.session["message"] = "address_edited"

        return redirect(previous_url)

    context = {
        "address": address,
        "previous_url": previous_url,
    }
    return render(request, "user/edit_address.html", context)


# Wallet
@login_required(login_url="authentication:signin")
def wallet(request):
    user = request.user.id
    try:
        if Wallet.objects.filter(user=user).exists():
            wallet = Wallet.objects.get(user=user)
            amount = wallet.amount
            transactions = WalletTransaction.objects.filter(wallet=wallet).order_by(
                "-id"
            )
            paginator = Paginator(transactions, 5)
            page_number = request.GET.get("page")
            transaction_obj = paginator.get_page(page_number)
        else:
            amount = 0.0
            transaction_obj = False
    except ObjectDoesNotExist:
        return redirect("authentication:signin")

    context = {
        "amount": amount,
        "transaction_obj": transaction_obj,
    }
    return render(request, "user/wallet.html", context)


# Change Password
@login_required(login_url="authentication:signin")
def change_password(request):
    message = False
    if request.method == "POST":
        current_password = request.POST.get("current_password")
        new_password = request.POST.get("new_password")
        user_id = request.user.id

        try:
            user = User.objects.get(id=user_id)
        except ObjectDoesNotExist:
            return redirect("authentication:signin")

        if user.check_password(current_password):
            user.set_password(new_password)
            user.save()
            message = "password_changed"
            return redirect("authentication:signin")
        else:
            message = "invalid_password"

    return render(request, "user/change_password.html", {"message": message})


# Download Product Invoice (PDF)
@login_required(login_url="authentication:signin")
def download_product_invoice(request, order_id):
    try:
        order = Orders.objects.get(id=order_id)
    except Orders.DoesNotExist:
        return HttpResponse("Order not found", status=404)

    context = {"order": order}
    template = get_template("user/invoice.html")
    html = template.render(context)

    result = BytesIO()
    pdf = pisa.pisaDocument(BytesIO(html.encode("UTF-8")), result)

    if pdf:
        response = HttpResponse(result.getvalue(), content_type="application/pdf")
        response["Content-Disposition"] = (
            f'attachment; filename="invoice_{order_id}.pdf"'
        )
        return response
    else:
        return HttpResponse("Error generating PDF", status=500)

wishlist/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse

from product.models import Product
from authentication.models import User
from wishlist.models import Wishlist


# Wishlist
@login_required(login_url="authentication:signin")
def wishlist(request):
    user_id = request.user.id
    products = (
        Wishlist.objects.filter(user=user_id).select_related("product").order_by("-id")
    )

    return render(request, "user/wishlist.html", {"products": products})


# Add to Wishlist
@login_required(login_url="authentication:signin")
def add_to_wishlist(request):
    product_id = request.GET.get("id")
    user_id = request.user.id

    response_data = {}

    if Wishlist.objects.filter(product=product_id, user=user_id).exists():
        response_data["message"] = "Item already in wishlist"
    else:
        try:
            product = Product.objects.get(id=product_id)
            user = User.objects.get(id=user_id)
            new_item = Wishlist.objects.create(product=product, user=user)
            new_item.save()
            response_data["message"] = "Item added to wishlist"
        except ObjectDoesNotExist:
            response_data["message"] = "Item not found"

    return JsonResponse(response_data, status=200)


# Remove from Wishlist
@login_required(login_url="authentication:signin")
def remove_from_wishlist(request, product_id):
    response_data = {}
    try:
        product = Wishlist.objects.get(id=product_id)
        product.delete()
        response_data["message"] = "Item removed"
    except ObjectDoesNotExist:
        response_data["message"] = "Item not in wishlist"
    return JsonResponse(response_data, status=200)

templates/user/address.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}Address{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'user/assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/magnific-popup/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/jquery.countdown.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/skins/skin-demo-13.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/demos/demo-13.css' %}">
    <style>
        .address-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-left: 1rem;
            margin-right: 0;
        }
        .address-container h2 {
            font-size: 20px;
            margin-bottom: 10px;
        }
        .address-container p {
            margin: 5px 0;
        }
        .address-container .name {
            font-weight: bold;
        }
        .address-container .city {
            margin-top: 10px;
        }
        .address-container .state,
        .address-container .zip,
        .address-container .country {
            display: inline-block;
            margin-right: 10px;
        }
        .address-container .state::after,
        .address-container .zip::after,
        .address-container .country::after {
            content: ",";
        }
        .address-container .state:last-child::after,
        .address-container .zip:last-child::after,
        .address-container .country:last-child::after {
            content: "";
        }
    </style>
{% endblock %}
{% block main %}
    <main class="main" style="margin-top: 50px; min-height: 45rem;">
        <div class="page-content">
            <div class="dashboard">
                <div class="container">
                    <div class="row">
                        <aside class="col-md-4 col-lg-3">
                            <ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:account_settings'  %}">Account Details</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:orders'  %}">Orders</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link active" href="{% url 'account:address'  %}">Adresses</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " href="{% url 'account:wallet'  %}">Wallet</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'account:change_password'  %}">Change Password</a>
                                </li>
                            </ul>
                        </aside>
                        <div class="col-md-8 col-lg-9">
                            <h3>Addresses</h3>
                            <div class="tab-content">
                                <div class="row">
                                    <a href="{% url 'account:add_address' %}" class="address-container col-6" style="margin-bottom: 1rem; border: 2px dashed #ccc; cursor: pointer; height: 263.8px;">
                                        <div>
                                            <div style="text-align: center; margin-top: 6rem; ">
                                                <span style="font-size: 50px; color: #3399ff; line-height: 1;">+</span>
                                                <h4 style="color: #3399ff;">Add Address</h4>
                                            </div>
                                        </div>
                                    </a>
                                    {% for address in addresses %}
                                        <div class="address-container col-6" style="margin-bottom: 1rem; height: 263.8px;">
                                            <p class="name">{{ address.name }}</p>
                                            <p class="street">{{ address.phone }}</p>
                                            <p class="street">{{ address.city }}</p>
                                            <p class="city">{{ address.landmark }}</p>
                                            <p class="state">{{ address.state }}</p>
                                            <p class="country">{{ address.country }}</p>
                                            <div class="row" style="margin-top: 1rem; position: absolute; top: 19rem;">
                                                <div class="col-6">
                                                    <button style="border: none; background: white;">
                                                        <a href="{% url 'account:edit_address' address.id %}" class="btn btn-primary text-white" style="border-radius: 30px;" >Edit</a>
                                                    </button>
                                                </div>
                                                <div class="col-6">
                                                    <button class="btn btn-danger text-white" onclick="confirmDelete({{ address.id }})" style="border-radius: 30px;">
                                                        Remove
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block js %}
    <script src="{% static 'user/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'user/assets/js/jquery.hoverIntent.min.js' %}"></script>
    <script src="{% static 'user/assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'user/assets/js/superfish.min.js' %}"></script>
    <script src="{% static 'user/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'user/assets/js/main.js' %}"></script>
{% endblock %}
{% block extra_js %}
    <script>
        function confirmDelete(addressId) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Remove',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                    var removeAddressUrl = "{% url 'account:remove_address' 123 %}";
                    removeAddressUrl = removeAddressUrl.replace('123', addressId);

                    window.location.href = removeAddressUrl;
                }
            });
        }

        {% if message == "address_added"%}
            const Toast = Swal.mixin({
                toast: true,
                position: "top-end",
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.onmouseenter = Swal.stopTimer;
                    toast.onmouseleave = Swal.resumeTimer;
                }
            });
            Toast.fire({
                icon: "success",
                title: "New Address Added"
            });
        {% endif %}

        {% if message == "address_edited"%}
            const Toast = Swal.mixin({
                toast: true,
                position: "top-end",
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.onmouseenter = Swal.stopTimer;
                    toast.onmouseleave = Swal.resumeTimer;
                }
            });
            Toast.fire({
                icon: "success",
                title: "Address Edited"
            });
        {% endif %}
    </script>
{% endblock %}

templates/user/order_success.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}Order Placed{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'user/assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/owl-carousel/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/magnific-popup/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/plugins/jquery.countdown.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/skins/skin-demo-13.css' %}">
    <link rel="stylesheet" href="{% static 'user/assets/css/demos/demo-13.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/tsparticles-confetti@2.12.0/tsparticles.confetti.bundle.min.js"></script>
{% endblock %}
{% block main %}
    <main class="main">
        <div class="page-content">
            <div class="checkout">
                <div class="container">
                    <div class="row" style="margin-top: 5rem; height: 30rem;">
                        <div class="col-lg-12" >
                            <div style="height: fit-content; width: 100%; display: flex; justify-content: center;">
                                <img width="94" height="94" src="https://img.icons8.com/3d-fluency/94/ok.png" alt="ok"/>
                            </div>
                            <div style="height: fit-content; width: 100%; display: flex; justify-content: center; margin-top: 4rem;">
                                <span style="font-size: 4rem; color: green; font-weight: 500;">Thank You</span>
                            </div>
                            <div style="height: fit-content; width: 100%; display: flex; justify-content: center;">
                                <span style="font-size: 2rem; font-weight: 500;">Your Order has been Placed!</span>
                            </div>
                            <div style="height: fit-content; width: 100%; display: flex; justify-content: center; margin-top: 4rem;">
                                <button style="border: none; background: #f9f9f9;">
                                    <a href="{% url 'home:home_page' %}" class="btn btn-primary text-white rounded-pill" style="min-width: 55px;" >Continue Shopping</a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block js %}
    <script src="{% static 'user/assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'user/assets/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'user/assets/js/jquery.hoverIntent.min.js' %}"></script>
    <script src="{% static 'user/assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'user/assets/js/superfish.min.js' %}"></script>
    <script src="{% static 'user/assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'user/assets/js/main.js' %}"></script>
{% endblock %}
{% block extra_js %}
    <script>
        const end = Date.now() + 3 * 1000;

        const colors = ["#bb0000", "#ffffff"];

        (function frame() {
            confetti({
                particleCount: 2,
                angle: 60,
                spread: 55,
                origin: {
                    x: 0
                },
                colors: colors,
            });

            confetti({
                particleCount: 2,
                angle: 120,
                spread: 55,
                origin: {
                    x: 1
                },
                colors: colors,
            });

            if (Date.now() < end) {
                requestAnimationFrame(frame);
            }
        })();
    </script>
{% endblock %}